language: python
python:
  - "2.7"
  - "3.5"
env:
  - LEKTOR=pypi
  - LEKTOR=master
matrix:
  exclude:
    - python: "3.5"
      env: LEKTOR=pypi

before_install:
  - curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.32.1/nvm.sh
  - source $HOME/.nvm/nvm.sh
  - nvm install stable
  - node --version
  - if [[ $LEKTOR == master ]]; then travis_retry pip install git+https://github.com/lektor/lektor.git#egg=Lektor; fi

install:
  - travis_retry pip install --upgrade pytest
  - travis_retry pip install --upgrade codecov
  - travis_retry pip install --editable .[test]

script: pytest --cov=lektor_webpack_support

after_success:
  - codecov
